### ISSUE TITLE
Will this gem support the redis 4 gem at any point?

### ISSUE THREAD

**Issue by antgel** [dmitrypol/redis_app_join#3]
As per subject. :)

**Comment by dmitrypol** [comment]
sorry, not working on this project anymore.  Happy to give you permissions to do the work

**Comment by antgel** [comment]
@dmitrypol Fair enough. I have another couple of questions - any way we can chat about this in private?  (We acquired Amplo Advance last year...)

Edit: *No longer relevant, thank you.* :)

**Comment by dmitrypol** [comment]
as you can see it's been years since I touched this code but I don't think why it would not be compatible w Redis 4 or higher.
